### ISSUE TITLE
Suggestion: Make the Webcam Preview Smaller

### ISSUE THREAD

**Issue by apintocr** [PatBQc/SeriousWebcamSettings#1]
First of all, thank you for developing this.

My suggestion is to make the video preview smaller, it takes a lot of space and makes the settings less easy to use.
Or give an option to turn the preview off (as most of the time it's not used because the camer is in-use on another app).

Thanks!

**Comment by PatBQc** [comment]
Hi @apintocr !

Ok so I guess you fired the nice message and forgot, but I just found your message in a bottle... my bad !

Yes that could be easy.  I was looking to do some fixes and build a new version: I could add that in it.

Are you still using the tool ?

Thanks a lot and have a great time !

Pat

**Comment by PatBQc** [comment]
There is now a neat option to turn off the preview as you can see in the screenshot:

![image](https://github.com/user-attachments/assets/e5ac970e-c222-4323-96c1-05fb2d7cd859)

As it is, the image does not show up per default with the new version, you must click the check box pour show the preview.

Thanks to @lunyx for that fix, hope it fixes your issue.

Thanks, 

Pat

**Comment by lunyx** [comment]
I think he wanted that space back instead of just blanking it out.  I had originally implemented this checkbox to prevent it from keeping my capture device in use on startup, not for any screen real estate issue.  I personally don't think there's any issue with configuring the settings, nor do I feel that it is difficult to use because of the space taken up by the preview, so I didn't address it.  I can see that a potential solution would be to have a way to collapse the preview to the left and have the other settings lay themselves out in a grid instead of a list, but it seemed like a lot of work for not much benefit.

**Comment by PatBQc** [comment]
Ok got it, started implementing the feature by adding a "Toggle Preview" button.

![image](https://github.com/user-attachments/assets/0e6e3fcd-c810-424c-a57c-28424ab4714a)

When pressed, it toggle into a smaller window

![image](https://github.com/user-attachments/assets/2b4cfdfc-9737-46f6-b6f6-95f892ac905a)

Clicking it again expands the window to it's original size.

No edge case optimised for the time being (like if you resize manually the window yourself while it's collapsed per example.)

**Comment by lunyx** [comment]
I think it could be tied to Show Preview so that it's not being duplicated.  I don't think there's a valid use case where you would want one but not the other.

**Comment by PatBQc** [comment]
Good point @lunyx .  Let's simplify that UX

**Comment by PatBQc** [comment]
Here, applied the proposed solution

Chose the webcam
![image](https://github.com/user-attachments/assets/b2695408-ab4d-41e3-a595-1abcf0df7535)

The default "collapsed" UI is used
![image](https://github.com/user-attachments/assets/2b167c77-f7e9-4d7a-b8f0-37c23910ba5c)

If you click on the "👀 Show Preview" it appears.
![image](https://github.com/user-attachments/assets/912e6e9d-4cde-45bc-ba5a-e384900c7e61)

Now the button shows "🙈 Hide Preview" that colapses back the window.
![image](https://github.com/user-attachments/assets/2b167c77-f7e9-4d7a-b8f0-37c23910ba5c)
