### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by petermeierrr** [PatBQc/SeriousWebcamSettings#2]
I'm experiencing similar issues to why you started this neat little tool, so I found myself quite thrilled to find your post on StackExchange!

In my company, the HW we use is rather strictly administrated. When working from home, I'm using a good widescreen camera. Unfortunately, I can't get its drivers installed to handle the cam settings properly. Whenever I enter a call on Teams or Zoom, the settings reset. I work in the living room and room mates show up on occasion if in widescreen view. Now, Teams removed the ability to directly control the camera, so my workaround is an old Lync installation, which gives me access. So I always go into those settings to change zoom and pan again directly after joining a call.

On my private PC, your tool works perfectly, but I can't run it on the work PC due to the lack of .net installation. I can't install the .net Framework either.

Hence the question:
Would you be able to provide a portable version, so compiled including the .net runtime (--self-contained)?

**Comment by PatBQc** [comment]
Hi @petermeierrr,

Sorry the issue was burried under a lot of other notifications, just read it... and really happy to see the project getting traction and helping folks!  

It's kind of new to me.

I would love to help but I don't have experience regarding building in the --self-contained fashion.  I can look into that to package a self contained without .net version.  Do you have experience with that ?

**Comment by petermeierrr** [comment]
Thank you very much for your reply.
Unfortunately not at all. I'm not much of a developer, I'm afraid.

**Comment by PatBQc** [comment]
Hi @petermeierrr,

I looked into it and I've built you some release (x64, x86 and ARM) that are self contained !

https://github.com/PatBQc/SeriousWebcamSettings/releases/tag/v1.2.0.1

Please, let me know if it works for you that way.

Have a wonderful time,

Pat

**Comment by petermeierrr** [comment]
Hi @PatBQc

Thank you for creating the self-contained versions! I'm just back from vacation and one of the first things was to try run it on my work PC. And it does work! It's indeed a wonderful time. :D

I look forward to put the program to action from now. I'll post a new ticket in case I face any issues.

**Comment by PatBQc** [comment]
Thanks @petermeierrr , great to hear !

Knowing that I helped is giving me a good boost for my day as well.  

Take care

Pat
