### ISSUE TITLE
license

### ISSUE THREAD

**Issue by murtazahassan2024** [PatBQc/SeriousWebcamSettings#3]
Is this an open source application,  allowing anyone to use, modify, and distribute the work? If yes I can't find the license.

**Comment by PatBQc** [comment]
Hi @murtazahassan2024 ,

Thanks a lot for the question, sorry it took so long to see it!  It was floating around somewhere in a sea of notifications.

I specified MIT Licence, so I guess you should be good to do anything you want with it.

[https://github.com/PatBQc/SeriousWebcamSettings/blob/master/LICENSE](https://github.com/PatBQc/SeriousWebcamSettings/blob/master/LICENSE)

I started accepting contributors as well, so feel free if that's your fun.

Take care !

Pat
